# Generated by Django 2.0.3 on 2018-04-25 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_fornecedor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.PessoaJuridica'),
        ),
    ]
