# Generated by Django 2.0.3 on 2018-05-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20180424_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Tamanho'),
        ),
    ]
