# Generated by Django 2.0.3 on 2018-06-01 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aquisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primeira_aquisicao', models.BooleanField(default=False)),
                ('data_aquisicao', models.DateTimeField(auto_now_add=True)),
                ('quantidade_produto', models.IntegerField(verbose_name='Quantidade adquirida')),
                ('produto_adiquirido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto')),
            ],
        ),
    ]
