# Generated by Django 2.0.3 on 2018-06-01 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0012_auto_20180523_1527'),
        ('produtos', '0004_aquisicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquisicao',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoas.Funcionario'),
            preserve_default=False,
        ),
    ]
