# Generated by Django 2.0.3 on 2018-06-01 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_aquisicao_funcionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aquisicao',
            old_name='produto_adiquirido',
            new_name='produto_adquirido',
        ),
    ]
