# Generated by Django 2.0.3 on 2018-05-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0012_auto_20180523_1527'),
        ('produtos', '0003_produto_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundo_caixa', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Fundo do Caixa')),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('caixa_aberto', models.BooleanField(default=True)),
                ('fechado_em', models.DateTimeField(auto_now=True)),
                ('aberto_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aberto_por', to='pessoas.Funcionario')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fechado_por', to='pessoas.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor pago')),
                ('tipo_pagamento', models.CharField(choices=[('CD', 'Débito'), ('CC', 'Crédito'), ('DI', 'Dinheiro')], default='DI', max_length=3, verbose_name='Tipo de Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoVendido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produto', models.IntegerField(verbose_name='Quantidade de Produtos')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor Total')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.Caixa')),
                ('cliente_pf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pf', to='pessoas.PessoaFisica')),
                ('cliente_pj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pj', to='pessoas.PessoaJuridica')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='produtovendido',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.Venda'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.Venda'),
        ),
    ]
