# Generated by Django 2.0.3 on 2018-05-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_caixa_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovendido',
            name='valor_produto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor do Produto'),
        ),
    ]
