# Generated by Django 2.0.3 on 2018-05-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_venda_venda_finalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='fechado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
