# Generated by Django 2.0.3 on 2018-05-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20180526_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='caixa_unico',
            field=models.BooleanField(default=False, verbose_name='Possuí um único vendedor?'),
        ),
    ]
