# Generated by Django 2.0.3 on 2018-05-29 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_movimentacao_troca'),
    ]

    operations = [
        migrations.AddField(
            model_name='troca',
            name='horario_troca',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='troca',
            name='motivo_troca',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='troca',
            name='valor_troca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Diferença de valor'),
        ),
    ]
