# Generated by Django 2.0.3 on 2018-05-31 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0012_auto_20180523_1527'),
        ('vendas', '0009_auto_20180528_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoas.Funcionario'),
            preserve_default=False,
        ),
    ]
