# Generated by Django 2.0.3 on 2018-06-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_movimentacao_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovendido',
            name='subtotal_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='SubTotal'),
        ),
    ]
