# Generated by Django 2.0.3 on 2018-08-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_produtovendido_subtotal_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMovimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=80, verbose_name='Categoria')),
                ('descricao_categoria', models.TextField(max_length=150, verbose_name='Descrição')),
            ],
        ),
    ]
