# Generated by Django 2.0.3 on 2018-08-14 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_categoriamovimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendas.CategoriaMovimentacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='movimenta_caixa',
            field=models.BooleanField(default=True, verbose_name='Retira dinheiro do caixa?'),
        ),
    ]
