# Generated by Django 2.0.3 on 2018-08-14 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0012_auto_20180523_1527'),
        ('vendas', '0013_auto_20180813_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_despesa', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor')),
                ('descricao_despesa', models.TextField(max_length=150, verbose_name='Descrição')),
                ('horario_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.CategoriaMovimentacao')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Funcionario')),
            ],
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='movimenta_caixa',
        ),
    ]
