# Generated by Django 2.0.3 on 2018-08-14 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_auto_20180813_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='horario_movimentacao',
            new_name='horario_despesa',
        ),
    ]
