# Generated by Django 2.0.3 on 2018-08-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0015_auto_20180813_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_pagamento_despesa',
            field=models.DateField(blank=True, null=True, verbose_name='Data de pagamento'),
        ),
    ]
