# Generated by Django 2.0.3 on 2018-08-30 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0017_auto_20180830_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='dia',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
