# Generated by Django 2.0.3 on 2018-04-17 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=50, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=6, verbose_name='Número')),
                ('bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('estado', models.CharField(max_length=30, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF_CNPJ', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone/Celular')),
                ('email', models.CharField(max_length=70, verbose_name='E-mail')),
                ('nome_pf', models.CharField(max_length=30, verbose_name='Nome')),
                ('sobrenome_pf', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('documento', models.CharField(max_length=15, verbose_name='R.G.')),
                ('uf_documento', models.CharField(max_length=6, verbose_name='UF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF_CNPJ', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone/Celular')),
                ('email', models.CharField(max_length=70, verbose_name='E-mail')),
                ('razao_social', models.CharField(max_length=80, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=80, verbose_name='Nome Fantasia')),
                ('insc_estadual', models.CharField(max_length=15, null=True, verbose_name='Inscrição Estadual')),
                ('contato', models.CharField(max_length=60, verbose_name='Pessoa para Contato')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoas.PessoaFisica')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('pessoas.pessoafisica',),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Endereco'),
        ),
    ]
