# Generated by Django 2.0.3 on 2018-04-17 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='empresa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.PessoaJuridica'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='morador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.PessoaFisica'),
        ),
    ]
