# Generated by Django 2.0.3 on 2018-04-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20180417_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='tipo_pessoa',
            field=models.CharField(choices=[(('FUN',), 'Funcionário'), ('EMP', 'Empresa'), ('FOR', 'Fornecedor'), ('CLI', 'Cliente')], default=('FUN',), max_length=3),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='tipo_pessoa',
            field=models.CharField(choices=[(('FUN',), 'Funcionário'), ('EMP', 'Empresa'), ('FOR', 'Fornecedor'), ('CLI', 'Cliente')], default=('FUN',), max_length=3),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.PessoaJuridica'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='morador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.PessoaFisica'),
        ),
    ]
