# Generated by Django 2.0.3 on 2018-04-18 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_auto_20180417_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='data_nascimento',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 18, 19, 16, 1, 427671)),
        ),
    ]
