# Generated by Django 2.0.3 on 2018-04-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_pessoafisica_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='data_nascimento',
            field=models.DateField(blank=True),
        ),
    ]
