# Generated by Django 2.0.3 on 2018-04-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_auto_20180418_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='id',
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='CPF_CNPJ',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='data_nascimento',
            field=models.DateField(blank=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='email',
            field=models.CharField(max_length=70, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='CPF_CNPJ',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='email',
            field=models.CharField(max_length=70, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='insc_estadual',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Inscrição Estadual'),
        ),
    ]
