# Generated by Django 2.0.3 on 2018-04-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_auto_20180420_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='tipo_pessoa',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='tipo_pessoa',
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='is_cliente',
            field=models.BooleanField(default=False, verbose_name='Cliente?'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='is_empresa',
            field=models.BooleanField(default=False, verbose_name='Empresa?'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='is_fornecedor',
            field=models.BooleanField(default=False, verbose_name='Fornecedor?'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='is_funcionario',
            field=models.BooleanField(default=False, verbose_name='Funcionário?'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='is_cliente',
            field=models.BooleanField(default=False, verbose_name='Cliente?'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='is_empresa',
            field=models.BooleanField(default=False, verbose_name='Empresa?'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='is_fornecedor',
            field=models.BooleanField(default=False, verbose_name='Fornecedor?'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='is_funcionario',
            field=models.BooleanField(default=False, verbose_name='Funcionário?'),
        ),
    ]
