# Generated by Django 2.0.3 on 2018-05-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0009_auto_20180424_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Salário'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_funcionario',
            field=models.CharField(choices=[('GER', 'Gerente'), ('EST', 'Estoquista'), ('VEN', 'Vendedor')], default='VEN', max_length=3),
        ),
    ]
