# Generated by Django 2.0.3 on 2018-05-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0010_auto_20180514_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='projeto/core/static/media', verbose_name='Logo da Empresa'),
        ),
    ]
