# Generated by Django 2.0.3 on 2018-05-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0011_pessoajuridica_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_funcionario',
            field=models.CharField(choices=[('GER', 'Gerente'), ('EST', 'Estoquista'), ('VEN', 'Vendedor')], default='VEN', max_length=3, verbose_name='Tipo de Funcionário'),
        ),
    ]
